name: Gravel
version: ${project.version}
main: org.jaoafa.gravel.Main
api-version: 1.18
softdepend:
  - MyMaid4
commands:
  loadplugin:
    description: プラグインをクローン・ビルドし、リロードします。
    usage: '/loadplugin'
  changeperm:
    description: あなたの権限グループを変更します。
    usage: '/changeperm <PermGroup>'

